services:
  server:
    container_name: memetic_server
    build:
      context: .
      dockerfile: server/Dockerfile
    image: memetic/server
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      # Add your server environment variables here
      NODE_ENV: production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 30s
      timeout: 10s
      retries: 3

  client:
    container_name: memetic_client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: memetic/client
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped
    environment:
      # Add your client environment variables here
      NODE_ENV: production